<?php include_once 'header.phtml'; ?>
    <div class="row-2">
    <section id="content">
        <div class="container_24">
            <div class="wrapper prev-indent-bot">
                <article class="grid_24">
                    <div class="box bg-1">
                        <img src="assets/hakkimizda-1.jpg" alt="Düzgün - design mobilya" class="spacing-bot" />
                        <div class="indent">
                            <h1>düzgün <span class="logo">dizayn mobilya</span></h1>
                            <div class="wrapper">
                                <figure class="img-indent">
                                    <img width="250"
                                         src="assets/hakkimizda-2.jpg"
                                         alt="Düzgün - design mobilya" class="border-white"/>
                                </figure>
                                <div class="extra-wrap">
                                    <h5 class="title">
                                        1990 yılında Özdemir Mobilya olarak
                                        kurulan ve daha sonra 23
                                        yıllık bilgi, birikim ve tecrübesini
                                        Düzgün Dizayn Mobilya adı
                                        altında yepyeni bir konseptle, hizmet ve
                                        kalite ilkelerinden
                                        vazgeçmeden bireysel ve kurumsal
                                        müşterilerimize sunmaya devam
                                        ediyoruz.</h5>

                                    <p>Mobilya imalatındaki tecrübemizi, en seçkin mobilya
                                        tasarımlarıyla birleştirerek çağdaş mobilya konseptinde, yeni
                                        bir bakış açısıyla, mobilyayı yeniden yorumluyoruz. Tüm mobilya
                                        tasarımlarımızda insanı ve mekansal ihtiyaçlarınızı göz önünde
                                        bulundurarak kaliteli ve ergonomik ürünler imal etmeyi
                                        hedefliyoruz.</p>
                                    <p>Düzgün Dizayn Mobilya olarak tüm ürünlerimizde 1nci sınıf
                                        malzemeler kullanmaktayız. Ürünlerimizi tamamen isteklerinize
                                        göre ister klasik, isterseniz de modern tasarıma göre dizayn
                                        ediyor, siz kullanıcılarımızın beğenisine göre devamlı olarak
                                        geliştirmelerimizi tamamlıyoruz.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
            <div class="wrapper">
                <article class="grid_24">
                    <div class="box bg-2 prev-indent-bot">
                        <div class="indent">
                            <h3 class="indent-bot">Referanslarımız</h3>
                            <ul class="referans">
                                <li>İstanbul Barosu</li>
                                <li>Papagan kuruyemiş</li>
                                <li>Biricik Şarap</li>
                                <li>Halıcıoğlu Askerlik Şubesi
                                <li>Genel Kurmay Başkanlıgı Hasdal Ekmek
                                    Fabrikası
                                </li>
                                <li>Başboğa Çadır A.Ş</li>
                                <li>Almanya – Berlin "Forever Clean"</li>
                                <li>Ankara "Forever Clean"</li>
                                <li>İstanbul "Forever Clean"</li>
                                <li>Gündem İnşaat</li>
                                <li>Amica Jeans</li>
                                <li>Leke Jeans</li>
                                <li>Çorlu Advantage AVM</li>
                                <li>Doğu Bank</li>
                                <li>Eminönü Yeraltı Çarşısı</li>
                                <li>İstanbul Milli Eğitim Müdürlügü (İstanbul
                                    genelinde 75 adet
                                    ilköğretim okulunun Atatürk köşesi yapıldı)
                                </li>
                            </ul>
                        </div>
                    </div>
                </article>
            </div>
        </div>
    </section>
    </div>
<?php include_once 'footer.phtml'; ?>