<!DOCTYPE html>
<html lang="en">
<head>
    <title>Düzgün Design <?php echo isset($titleExtension) ? ' - ' . $titleExtension : '' ?></title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="css/reset.css" type="text/css" media="screen">
    <link rel="stylesheet" href="css/style.css" type="text/css" media="screen">
    <link rel="stylesheet" href="css/grid24.css" type="text/css" media="screen">
    <script src="js/jquery-1.6.4.min.js" type="text/javascript"></script>
<!--    <script src="js/jquery-1.9.1.min.js" type="text/javascript"></script>-->
    <script src="js/ff_cash.js" type="text/javascript"></script>
    <script src="js/superfish.js" type="text/javascript"></script>
    <?php if ($page == 'index') : ?>
    <script src="js/jquery.prettyPhoto.js" type="text/javascript"></script>
    <script src="js/tms-0.3.2.js" type="text/javascript"></script>
    <script src="js/tms_presets.js" type="text/javascript"></script>
    <?php endif; ?>
    <?php if ($page == 'iletisim') : ?>
    <script src="js/forms.js" type="text/javascript"></script>
    <?php endif; ?>
    <?php if (in_array($page, array('mutfak','banyo','gardrop','sifonyer','tv','makyaj','kitaplik','kapi' ))): ?>
        <link rel="stylesheet" href="css/slimbox2.css" type="text/css" media="screen" />
        <script type="text/javascript" src="js/slimbox2.js"></script>
        <script type="text/javascript">
            $(document).ready(function(){
                jQuery("#gallery a").slimbox();
            });
        </script>
    <?php endif; ?>
    <!--[if lt IE 7]>
    <div style='clear:both; text-align:center; position:relative;'><a
        href="http://windows.microsoft.com/en-US/internet-explorer/products/ie/home?ocid=ie6_countdown_bannercode"><img
        src="http://storage.ie6countdown.com/assets/100/images/banners/warning_bar_0000_us.jpg"
        border="0" height="42" width="820"
        alt="Eski bir tarayıcı kullanıyorsunuz.Daha hızlı ve güvenli internet kullanımı için, tarayıcınızı hemen şimdi yenileyin."/></a>
    </div>
    <![endif]-->
    <!--[if lt IE 9]>
    <script type="text/javascript" src="js/html5.js"></script>
    <link rel="stylesheet" href="css/ie.css" type="text/css" media="screen">
    <![endif]-->
</head>
<body <?= ($page=='index') ? 'id="page1"':'' ?>>
<div class="block">
<!--==============================header=================================-->
<header class="header">
    <div class="row-1">
        <div class="main">
            <div class="logo"><a href="index.php">Morcan</a></div>
            <nav>
                <ul class="sf-menu">
                    <li><a <?= $page == 'index' ? 'class="current"' :'' ?> href="index.php">ANA SAYFA</a></li>
                    <li><a <?= $page == 'hakkimizda' ? 'class="current"' :'' ?>  href="hakkimizda.php">HAKKIMIZDA</a></li>
                    <li><a <?= in_array($page, array('mutfak','banyo','gardrop','sifonyer','tv','makyaj','kitaplik','kapi')) ? 'class="current"' :'' ?> href="#">ÜRÜNLERİMİZ</a>
                        <ul>
                            <li>
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/01-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="mutfak.php">Mutfak Dolapları</a>
                                    </div>
                                </div>
                            </li>
                            <li class="item">
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/02-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="banyo.php">Banyo Dolapları</a>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/03-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="gardrop.php">Gardroplar</a>
                                    </div>
                                </div>
                            </li>
                            <li class="item">
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/04-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="sifonyer.php">Şifonyerler</a>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/05-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="tv.php">TV Üniteleri</a>
                                    </div>
                                </div>
                            </li>
                            <li class="item">
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/06-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="makyaj.php">Makyaj Masaları</a>
                                    </div>
                                </div>
                            </li>
                            <li>
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/07-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="kitaplik.php">Kitaplık Modelleri</a>
                                    </div>
                                </div>
                            </li>
                            <li class="item">
                                <div class="wrapper">
                                    <figure class="menu-img">
                                        <img src="assets/00-start/08-thumb-m.jpg" width="61" height="51" alt="">
                                    </figure>
                                    <div class="extra-wrap">
                                        <a href="kapi.php">Kapı Modelleri</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <li<?= $page == 'contact' ? 'class="current"' :'' ?>><a href="iletisim.php">İLETİŞİM</a></li>
                </ul>
            </nav>
        </div>
    </div>
</header>
<!--==============================End header=================================-->