<?php include_once 'header.phtml'; ?>
    <div class="row-2">
        <div class="indent">
            <h3 class="p2">İletişim</h3>

            <div class="container_24">
                <div class="wrapper prev-indent-bot">
                    <div class="box bg-1 maxheight-1 fleft border-white"
                         style="width: 450px; height: 282px; overflow:hidden;">
                        <img src="assets/hakkimizda-1.jpg"
                             alt="Düzgün - design mobilya" class="spacing-bot"
                             style="width: 450px;"/>
                    </div>
                    <div class="box bg-1 maxheight-1 fright border-white"
                         style="width: 450px; height: 282px; overflow:hidden; margin-right: 20px;">
                        <img src="assets/hakkimizda-2.jpg"
                             alt="Düzgün - design mobilya" class="spacing-bot"
                             style="width: 450px;"/>
                    </div>
                </div>
            </div>
            <div class="container_24">
                <div class="wrapper prev-indent-bot">
                    <div class="box maxheight-1" style="width: 450px; float:left; margin-right: 30px">
                        <p class="alignright"><strong>Showroom</strong><br/>
                        Çırçır Mah. Namık Kemal Cad. No:124<br/>
                        Alibeyköy / Eyüp – İstanbul<br/>
                        Tel & Faks : 0 212 427 20 62<br/>
                        e-mail : duzgundizayn@mail.com<br/>
                        </p>
                    </div>
                    <div class="box maxheight-1" style="margin-right: 20px; width: 450px; float:left;">
                        <p style="padding-left:5px;"><strong>İmalat</strong><br/>
                        Yeşilpınar Mah. Semerkant Sok. No:31<br/>
                        Alibeyköy / Eyüp – İstanbul<br/>
                        Tel & Fax: 0 212 535 9736 <br />
                            Cep: 0533 963 91 63
                        </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
    </div>
<?php include_once 'footer.phtml'; ?>