<?php include_once 'header.phtml'; ?>
<div class="row-2">
        <div class="main">
            <div class="slider">
                <ul class="items">
                    <li><img src="assets/00-start/01-big.jpg" alt=""></li>
                    <li><img src="assets/00-start/02-big.jpg" alt=""></li>
                    <li><img src="assets/00-start/03-big.jpg" alt=""></li>
                    <li><img src="assets/00-start/04-big.jpg" alt=""></li>
                    <li><img src="assets/00-start/05-big.jpg" alt=""></li>
                    <li><img src="assets/00-start/06-big.jpg" alt=""></li>
                    <li><img src="assets/00-start/07-big.jpg" alt=""></li>
                    <li><img src="assets/00-start/08-big.jpg" alt=""></li>
                </ul>
                <ul class="pagination">
                    <li><a class="item1" href="#"></a><span></span></li>
                    <li><a class="item2" href="#"></a><span></span></li>
                    <li><a class="item3" href="#"></a><span></span></li>
                    <li><a class="item4" href="#"></a><span></span></li>
                    <li><a class="item5" href="#"></a><span></span></li>
                    <li><a class="item6" href="#"></a><span></span></li>
                    <li><a class="item7" href="#"></a><span></span></li>
                    <li class="last-item"><a class="item8" href="#"></a><span></span></li>
                </ul>
            </div>
        </div>
    </div>
<?php include_once 'footer.phtml'; ?>