<?php
$page='index';
?>
<?php include_once 'header.phtml'; ?>
<div class="row-2">
        <div class="main">
            <div class="slider">
                <ul class="items">
                    <li><img src="images/page1-img1-big.jpg" alt=""></li>
                    <li><img src="images/page1-img2-big.jpg" alt=""></li>
                    <li><img src="images/page1-img3-big.jpg" alt=""></li>
                    <li><img src="images/page1-img4-big.jpg" alt=""></li>
                    <li><img src="images/page1-img5-big.jpg" alt=""></li>
                    <li><img src="images/page1-img6-big.jpg" alt=""></li>
                </ul>
                <ul class="pagination">
                    <li><a class="item1" href="#"></a><span></span></li>
                    <li><a class="item2" href="#"></a><span></span></li>
                    <li><a class="item3" href="#"></a><span></span></li>
                    <li><a class="item4" href="#"></a><span></span></li>
                    <li><a class="item5" href="#"></a><span></span></li>
                    <li class="last-item"><a class="item6" href="#"></a><span></span></li>
                </ul>
            </div>
        </div>
    </div>
<?php include_once 'footer.phtml'; ?>